//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Library
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Book.
    /// </summary>
    //  *** Start programmer edit section *** (Book CustomAttributes)

    //  *** End programmer edit section *** (Book CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BookE", new string[] {
            "Name as \'Name\'"})]
    [View("BookL", new string[] {
            "Name as \'Name\'"})]
    public class Book : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (Book CustomMembers)

        //  *** End programmer edit section *** (Book CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Name CustomAttributes)

        //  *** End programmer edit section *** (Book.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Name Get start)

                //  *** End programmer edit section *** (Book.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Book.Name Get end)

                //  *** End programmer edit section *** (Book.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Name Set start)

                //  *** End programmer edit section *** (Book.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Book.Name Set end)

                //  *** End programmer edit section *** (Book.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BookE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookE", typeof(IIS.Library.Book));
                }
            }
            
            /// <summary>
            /// "BookL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookL", typeof(IIS.Library.Book));
                }
            }
        }
    }
}
